import { LEADS_API_BASE_URL, LEADS_API_KEY } from "astro:env/server";
import { parseSitemap } from "../sitemap-parser.js";
import { getServices } from "./services";
import type { SitemapPage } from "../regional-sitemap";

let cache: { pages: SitemapPage[]; expiresAt: number } | undefined;
let pending: Promise<SitemapPage[]> | undefined;

/** Old CMS URLs remain valid entry points, with one redirect to the frontend route. */
export async function legacyContentPath(path: string): Promise<string> {
  if (path.startsWith("/services/")) {
    const service = (await getServices()).find(service => service.cmsPath === path);
    if (service) return service.url;
  }
  return path;
}

export async function getCmsSitemapPages(): Promise<SitemapPage[]> {
  if (cache && cache.expiresAt > Date.now()) return cache.pages;
  if (pending) return pending;
  pending = fetchPages().then(pages => {
    cache = { pages, expiresAt: Date.now() + 60_000 };
    return pages;
  }).finally(() => { pending = undefined; });
  return pending;
}

async function fetchPages(): Promise<SitemapPage[]> {
  if (!LEADS_API_KEY) throw new Error("W1DO API key is not configured.");
  const baseUrl = LEADS_API_BASE_URL || "https://backend.w1do.ru";
  const options = {
    headers: { Accept: "application/xml", "X-Api-Key": LEADS_API_KEY },
    signal: AbortSignal.timeout(10000),
  };
  let response = await fetch(new URL("/api/v1/sitemap.xml", baseUrl), options);
  // Older deployed W1DO versions expose the same project-scoped API at the root.
  if (response.status === 404) response = await fetch(new URL("/sitemap.xml", baseUrl), {
    ...options, signal: AbortSignal.timeout(10000),
  });
  if (!response.ok) throw new Error(`W1DO sitemap returned HTTP ${response.status}.`);
  const services = await getServices();
  const aliases = new Map(services.map(service => [service.cmsPath, service.url]));
  return parseSitemap(await response.text()).map((page): SitemapPage | undefined => {
    const url = new URL(page.loc);
    if (!["w1do.ru", "www.w1do.ru"].includes(url.hostname)) throw new Error("W1DO sitemap contains an unrelated host.");
    let path = url.pathname.replace(/\/$/, "") || "/";
    path = aliases.get(path) || path;
    // City landing URLs are generated by the frontend's own sitemap.
    if (path.startsWith("/cities/")) return undefined;
    if (path === "/categories" || path.startsWith("/categories/")) path = `/blog${path}`;
    return { path, lastmod: page.lastmod, changefreq: page.changefreq, priority: page.priority };
  }).filter((page): page is SitemapPage => Boolean(page));
}
